### ISSUE TITLE
Retorno

### ISSUE THREAD

**Issue by bralandealmeida** [Guilherme-fagundes/Consulta_cnpj#1]
Fiz a instalação do pacote em um projeto Laravel. Saberia informar consigo obter o retorno da consulta?

**Comment by Guilherme-fagundes** [comment]
Foi atualizada para para Rodar no laravel

Basta rodar o comando do composer require pra baixar a nova versão 

composer require guilherme-fagundes/consultacnpj

Qualquer dúvida estou a disposição
Abraço!
